FROM node:18-alpine

WORKDIR /app

COPY package.json ./
COPY package-lock.json ./
COPY tsconfig.json ./
COPY ./prisma ./prisma

RUN npm install

COPY . ./

EXPOSE 3333

CMD [ "npm", "run", "start:dev" ]